const firebaseConfig = {
    apiKey: "AIzaSyCBk1dt3vKyHO3-RIm6TBqC2GpCxiZTvfQ",
    authDomain: "fernando-bce22.firebaseapp.com",
    databaseURL: "https://fernando-bce22-default-rtdb.firebaseio.com",
    projectId: "fernando-bce22",
    storageBucket: "fernando-bce22.firebasestorage.app",
    messagingSenderId: "909134111459",
    appId: "1:909134111459:web:dc75f291b972f664999bd6",
};

const projectData = {
    pimental: {
        name: "Pimental",
        linhas: {
            "01": { metragem: 88.63, bases: { A: 1, C: 5, E: 1, K: 6 } },
            "02": { metragem: 90.63, bases: { C: 6, G: 1, K: 6 } },
            "03": { metragem: 88.63, bases: { B: 1, D: 5, F: 1, K: 6 } },
            "04": { metragem: 90.63, bases: { D: 6, H: 1, K: 6 } },
            "05": { metragem: 18.585, bases: { J: 1 } },
            "06": { metragem: 18.585, bases: { J: 1 } },
            "07": { metragem: 18.585, bases: { J: 1 } },
            "08": { metragem: 18.585, bases: { J: 1 } },
            "09": { metragem: 18.585, bases: { J: 1 } },
            10: { metragem: 18.585, bases: { J: 1 } },
            11: { metragem: 18.585, bases: { J: 1 } },
            12: { metragem: 18.585, bases: { J: 1 } },
            13: { metragem: 18.585, bases: { J: 1 } },
            14: { metragem: 18.585, bases: { J: 1 } },
            15: { metragem: 18.585, bases: { J: 1 } },
            16: { metragem: 18.585, bases: { J: 1 } },
            17: { metragem: 18.585, bases: { J: 1 } },
            18: { metragem: 18.585, bases: { J: 1 } },
        },
    },
    "belo-monte": {
        name: "Belo Monte",
        linhas: {
            "01": { metragem: 89.485, bases: { A: 1, C: 5, E: 1, K: 5 } },
            "02": { metragem: 90.085, bases: { C: 5, E: 1, K: 6 } },
            "03": { metragem: 98.82, bases: { C: 5, E: 1, K: 6 } },
            "04": { metragem: 98.82, bases: { C: 5, E: 1, K: 6 } },
            "05": { metragem: 99.43, bases: { C: 5, E: 1, K: 6 } },
            "06": { metragem: 98.82, bases: { C: 5, E: 1, K: 6 } },
            "07": { metragem: 98.82, bases: { C: 5, E: 1, K: 6 } },
            "08": { metragem: 98.777, bases: { C: 5, E: 1, K: 6 } },
            "09": { metragem: 64.514, bases: { C: 3, G: 1, K: 3 } },
            10: { metragem: 89.485, bases: { B: 1, D: 5, F: 1, K: 5 } },
            11: { metragem: 90.085, bases: { C: 5, F: 1, K: 6 } },
            12: { metragem: 98.82, bases: { C: 5, F: 1, K: 6 } },
            13: { metragem: 98.82, bases: { C: 5, F: 1, K: 6 } },
            14: { metragem: 99.43, bases: { C: 5, F: 1, K: 6 } },
            15: { metragem: 98.82, bases: { C: 5, F: 1, K: 6 } },
            16: { metragem: 98.82, bases: { C: 5, F: 1, K: 6 } },
            17: { metragem: 98.777, bases: { C: 5, F: 1, K: 6 } },
            18: { metragem: 64.514, bases: { D: 3, H: 1, K: 3 } },
            19: { metragem: 31.9, bases: { J: 3 } },
            20: { metragem: 31.9, bases: { J: 3 } },
            21: { metragem: 31.9, bases: { J: 3 } },
            22: { metragem: 31.9, bases: { J: 3 } },
            23: { metragem: 31.9, bases: { J: 3 } },
            24: { metragem: 31.9, bases: { J: 3 } },
            25: { metragem: 31.9, bases: { J: 3 } },
            26: { metragem: 31.9, bases: { J: 3 } },
            27: { metragem: 31.9, bases: { J: 3 } },
            28: { metragem: 31.9, bases: { J: 3 } },
            29: { metragem: 31.9, bases: { J: 3 } },
            30: { metragem: 31.9, bases: { J: 3 } },
            31: { metragem: 31.9, bases: { J: 3 } },
            32: { metragem: 31.9, bases: { J: 3 } },
            33: { metragem: 31.9, bases: { J: 3 } },
            34: { metragem: 31.9, bases: { J: 3 } },
            35: { metragem: 31.9, bases: { J: 3 } },
            36: { metragem: 31.9, bases: { J: 3 } },
            37: { metragem: 31.9, bases: { J: 3 } },
            38: { metragem: 31.9, bases: { J: 3 } },
            39: { metragem: 31.9, bases: { J: 3 } },
            40: { metragem: 31.9, bases: { J: 3 } },
            41: { metragem: 31.9, bases: { J: 3 } },
            42: { metragem: 31.9, bases: { J: 3 } },
            43: { metragem: 31.9, bases: { J: 3 } },
            44: { metragem: 31.9, bases: { J: 3 } },
            45: { metragem: 31.9, bases: { J: 3 } },
            46: { metragem: 31.9, bases: { J: 3 } },
            47: { metragem: 31.9, bases: { J: 3 } },
            48: { metragem: 31.9, bases: { J: 3 } },
            49: { metragem: 31.9, bases: { J: 3 } },
            50: { metragem: 31.9, bases: { J: 3 } },
            51: { metragem: 31.9, bases: { J: 3 } },
            52: { metragem: 31.9, bases: { J: 3 } },
            53: { metragem: 31.9, bases: { J: 3 } },
            54: { metragem: 31.9, bases: { J: 3 } },
            55: { metragem: 31.9, bases: { J: 3 } },
            56: { metragem: 31.9, bases: { J: 3 } },
            57: { metragem: 31.9, bases: { J: 3 } },
            58: { metragem: 31.9, bases: { J: 3 } },
            59: { metragem: 31.9, bases: { J: 3 } },
            60: { metragem: 31.9, bases: { J: 3 } },
            61: { metragem: 31.9, bases: { J: 3 } },
            62: { metragem: 31.9, bases: { J: 3 } },
            63: { metragem: 31.9, bases: { J: 3 } },
            64: { metragem: 31.9, bases: { J: 3 } },
            65: { metragem: 31.9, bases: { J: 3 } },
            66: { metragem: 31.9, bases: { J: 3 } },
            67: { metragem: 31.9, bases: { J: 3 } },
            68: { metragem: 31.9, bases: { J: 3 } },
            69: { metragem: 31.9, bases: { J: 3 } },
            70: { metragem: 31.9, bases: { J: 3 } },
            71: { metragem: 31.9, bases: { J: 3 } },
        },
    },
    oficina: {
        name: "Oficina",
        linhas: {
            72: { metragem: 25.0, bases: { M: 2, B: 1 } },
            73: { metragem: 25.0, bases: { K: 2 } },
            74: { metragem: 25.0, bases: { B: 1, H: 1 } },
        },
    },
};

const progressData = {
    pimental: {
        "01": { A: 0, C: 0, E: 0, K: 0 },
        "02": { C: 0, G: 0, K: 0 },
        "03": { B: 0, D: 0, F: 0, K: 0 },
        "04": { D: 0, H: 0, K: 0 },
        "05": { J: 0 },
        18: { J: 0 },
    },
    "belo-monte": {
        "01": { A: 0, C: 0, E: 0, K: 0 },
        "02": { C: 0, E: 0, K: 0 },
        "03": { C: 0, E: 0, K: 0 },
        "04": { C: 0, E: 0, K: 0 },
        "05": { C: 0, E: 0, K: 0 },
        "06": { C: 0, E: 0, K: 0 },
        "07": { C: 0, E: 0, K: 0 },
        "08": { C: 0, E: 0, K: 0 },
        "09": { C: 0, G: 0, K: 0 },
        10: { B: 0, D: 0, F: 0, K: 0 },
        11: { C: 0, F: 0, K: 0 },
        12: { C: 0, F: 0, K: 0 },
        13: { C: 0, F: 0, K: 0 },
        14: { C: 0, F: 0, K: 0 },
        15: { C: 0, F: 0, K: 0 },
        16: { C: 0, F: 0, K: 0 },
        17: { C: 0, F: 0, K: 0 },
        18: { D: 0, H: 0, K: 0 },
        19: { J: 3 },
        71: { J: 0 },
    },
    oficina: {
        72: { M: 0, B: 0 },
        73: { K: 0 },
        74: { B: 0, H: 0 },
    },
};

const lineStepsStatus = {
    pimental: {
        "01": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "02": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "03": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "04": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "05": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        18: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
    },
    "belo-monte": {
        "01": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "02": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "03": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "04": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "05": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "06": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "07": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "08": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        "09": {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        10: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        11: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        12: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        13: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        14: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        15: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        16: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        17: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        18: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        19: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        71: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
    },
    oficina: {
        72: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        73: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
        74: {
            passagemCabo: false,
            crimpagemCabo: false,
            afericaoCrimpagem: false,
            tensionamentoCabo: false,
            lacreTensionador: "",
            lacreLoopAbs: "",
        },
    },
};

const lineObservations = {
    pimental: {
        "01": "",
        "02": "",
        "03": "",
        "04": "",
        "05": "",
        18: "",
    },
    "belo-monte": {
        "01": "",
        "02": "",
        "03": "",
        "04": "",
        "05": "",
        "06": "",
        "07": "",
        "08": "",
        "09": "",
        10: "",
        11: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        71: "",
    },
    oficina: {
        72: "",
        73: "",
        74: "",
    },
};

const teamConfig = {
    pessoas: 4,
    horasPorDia: 6,
    aproveitamento: 0.8,
    inicioTrabalhoBruto: new Date("2025-09-11"),
    dataAtual: new Date(),
};

const state = {
    firebaseConfig,
    db: null,
    currentProjectId: null,
    allowOnlineEdits: false,
    PROJECT_PASSWORD_HASH: null,
    isAuthenticated: false,
    pendingAction: null,
    projectData,
    progressData,
    lineStepsStatus,
    lineObservations,
    builtInformations: {},
    builtEditBackup: null,
    teamConfig,
    executionDates: {},
    manualActiveUsina: null,
    chartConclusaoGeral: null,
};

function createSetter(key) {
    return (value) => {
        state[key] = value;
        return value;
    };
}

export const setDb = createSetter("db");
export const setCurrentProjectId = createSetter("currentProjectId");
export const setAllowOnlineEdits = createSetter("allowOnlineEdits");
export const setProjectPasswordHash = createSetter("PROJECT_PASSWORD_HASH");
export const setIsAuthenticated = createSetter("isAuthenticated");
export const setPendingAction = createSetter("pendingAction");
export const setProgressData = createSetter("progressData");
export const setLineStepsStatus = createSetter("lineStepsStatus");
export const setLineObservations = createSetter("lineObservations");
export const setBuiltInformations = createSetter("builtInformations");
export const setBuiltEditBackup = createSetter("builtEditBackup");
export const setTeamConfig = createSetter("teamConfig");
export const setExecutionDates = createSetter("executionDates");
export const setManualActiveUsina = createSetter("manualActiveUsina");
export const setChartConclusaoGeral = createSetter("chartConclusaoGeral");

export default state;
